/* ══════════════════════════════════════
   PRODUCTS.JS — Q-tech база товаров
   ══════════════════════════════════════ */

const PRODUCTS = [

  /* ── PHONES ── */
  {
    id: 1,
    title: 'Apple iPhone 16 Pro 256Gb Natural Titanium',
    brand: 'Apple',
    category: 'phones',
    price: 99990,
    oldPrice: 114990,
    rating: 4.9,
    reviews: 312,
    badge: 'hit',
    inStock: true,
    images: [
      'img/grey-16-1.webp',
      'img/grey-16-2.webp',
      'img/grey-16-3.webp',
      'img/grey-16-4.webp',
      'img/grey-16-5.webp',
    ],
    colorVariants: [
      { id: 1, colorCode: 'orange', colorName: 'Натуральный титан', hex: '#C2BCB2' },
      { id: 4, colorCode: 'silver', colorName: 'Серебристый', hex: '#C0C0C0' },
    ],
    description: 'iPhone 16 Pro — новый уровень производительности с чипом A18 Pro, революционными кнопками управления и профессиональной камерой на 48 МП.',
    specs: {
      'Экран': '6.3" Super Retina XDR, 120 Гц',
      'Процессор': 'Apple A18 Pro',
      'Память': '256 ГБ',
      'ОЗУ': '8 ГБ',
      'Камера': '48 МП + 12 МП + 12 МП',
      'Батарея': '3582 мАч',
      'ОС': 'iOS 18',
      'Цвет': 'Natural Titanium',
    }
  },
  {
    id: 2,
    title: 'Apple iPhone 15 Pro Max 256Gb Black Titanium',
    brand: 'Apple',
    category: 'phones',
    price: 89990,
    oldPrice: null,
    rating: 4.8,
    reviews: 540,
    badge: null,
    inStock: true,
    images: [
      'img/grey-15-1.webp',
      'img/grey-15-2.webp',
      'img/grey-15-3.webp',
      'img/grey-15-4.webp',
      'img/grey-15-5.webp',
      'img/grey-15-6.webp',
    ],
    colorVariants: [
      { id: 8, colorCode: 'grey', colorName: 'Серый',     hex: '#9E9E9E' },
      { id: 6, colorCode: 'gren', colorName: 'Зелёный',   hex: '#4CAF50' },
      { id: 3, colorCode: 'pink', colorName: 'Розовый',   hex: '#F06292' },
      { id: 7, colorCode: 'yel',  colorName: 'Жёлтый',    hex: '#FDD835' },
      { id: 2, colorCode: 'bl',   colorName: 'Голубой',   hex: '#1565C0' },
    ],
    description: 'iPhone 15 Pro Max с корпусом из титана, чипом A17 Pro и оптическим зумом 5x.',
    specs: {
      'Экран': '6.7" Super Retina XDR, 120 Гц',
      'Процессор': 'Apple A17 Pro',
      'Память': '256 ГБ',
      'ОЗУ': '8 ГБ',
      'Камера': '48 МП + 12 МП + 12 МП',
      'Батарея': '4422 мАч',
      'ОС': 'iOS 17',
      'Цвет': 'Black Titanium',
    }
  },
  {
    id: 3,
    title: 'Apple iPhone 15 128Gb Pink',
    brand: 'Apple',
    category: 'phones',
    price: 59990,
    oldPrice: 69990,
    rating: 4.7,
    reviews: 228,
    badge: 'sale',
    inStock: true,
    images: [
      'img/pink-1.webp',
      'img/pink-2.webp',
      'img/pink-3.webp',
      'img/pink-4.webp',
      'img/pink-5.webp',
      'img/pink-6.webp',
    ],
    colorVariants: [
      { id: 8, colorCode: 'grey', colorName: 'Серый',     hex: '#9E9E9E' },
      { id: 6, colorCode: 'gren', colorName: 'Зелёный',   hex: '#4CAF50' },
      { id: 3, colorCode: 'pink', colorName: 'Розовый',   hex: '#F06292' },
      { id: 7, colorCode: 'yel',  colorName: 'Жёлтый',    hex: '#FDD835' },
      { id: 2, colorCode: 'bl',   colorName: 'Голубой',   hex: '#1565C0' },
    ],
    description: 'iPhone 15 с Dynamic Island, камерой 48 МП и чипом A16 Bionic.',
    specs: {
      'Экран': '6.1" Super Retina XDR',
      'Процессор': 'Apple A16 Bionic',
      'Память': '128 ГБ',
      'Камера': '48 МП + 12 МП',
      'Батарея': '3877 мАч',
      'ОС': 'iOS 17',
      'Цвет': 'Pink',
    }
  },
  {
    id: 4,
    title: 'Apple iPhone 17 Pro 256ГБ Silver',
    brand: 'Apple',
    category: 'phones',
    price: 20990,
    oldPrice: null,
    rating: 4.5,
    reviews: 180,
    badge: null,
    inStock: true,
    images: [
      'img/silver-17-3.webp',
      'img/silver-17-4.webp',
      'img/silver-17-1.jpg.webp',
      'img/silver-17-2.jpg.webp',
    ],
    colorVariants: [
      { id: 1, colorCode: 'orange', colorName: 'Оранжевый', hex: '#E8631A' },
      { id: 4, colorCode: 'silver', colorName: 'Серебристый', hex: '#C0C0C0' },
    ],
    description: 'Apple iPhone 17 Pro — доступный iPhone с Liquid Retina дисплеем и чипом A12 Bionic.',
    specs: {
      'Экран': '6.3" Super Retina',
      'Процессор': 'Apple A19 Pro, 6',
      'Память': '256 ГБ',
      'Камера': '48+48+48 МП',
      'Батарея': '3988 мАч',
      'ОС': 'iOS 16',
      'Цвет': 'Silver',
    }
  },
  {
    id: 5,
    title: 'Apple iPhone 15 Pro 256Gb Blue Titanium',
    brand: 'Apple',
    category: 'phones',
    price: 79990,
    oldPrice: 89990,
    rating: 4.8,
    reviews: 410,
    badge: 'sale',
    inStock: true,
    images: [
      'img/blue-15-1.webp',
      'img/blue-15-2.webp',
      'img/blue-15-3.webp',
      'img/blue-15-4.webp',
    ],
    colorVariants: [
      { id: 8, colorCode: 'grey', colorName: 'Серый',     hex: '#9E9E9E' },
      { id: 6, colorCode: 'gren', colorName: 'Зелёный',   hex: '#4CAF50' },
      { id: 3, colorCode: 'pink', colorName: 'Розовый',   hex: '#F06292' },
      { id: 7, colorCode: 'yel',  colorName: 'Жёлтый',    hex: '#FDD835' },
      { id: 2, colorCode: 'bl',   colorName: 'Голубой',   hex: '#1565C0' },
    ],
    description: 'iPhone 15 Pro в цвете Blue Titanium с чипом A17 Pro и Action Button.',
    specs: {
      'Экран': '6.1" Super Retina XDR, 120 Гц',
      'Процессор': 'Apple A17 Pro',
      'Память': '256 ГБ',
      'Камера': '48 МП + 12 МП + 12 МП',
      'Батарея': '3274 мАч',
      'ОС': 'iOS 17',
      'Цвет': 'Blue Titanium',
    }
  },
  {
    id: 6,
    title: 'Apple iPhone 15 128Gb Green',
    brand: 'Apple',
    category: 'phones',
    price: 54990,
    oldPrice: null,
    rating: 4.6,
    reviews: 198,
    badge: null,
    inStock: true,
    images: [
      'img/gren-1.webp',
      'img/gren-2.webp',
      'img/gren-3.webp',
      'img/gren-4.webp',
      'img/gren-5.webp',
      'img/gren-6.webp',
    ],
    colorVariants: [
      { id: 8, colorCode: 'grey', colorName: 'Серый',     hex: '#9E9E9E' },
      { id: 6, colorCode: 'gren', colorName: 'Зелёный',   hex: '#4CAF50' },
      { id: 3, colorCode: 'pink', colorName: 'Розовый',   hex: '#F06292' },
      { id: 7, colorCode: 'yel',  colorName: 'Жёлтый',    hex: '#FDD835' },
      { id: 2, colorCode: 'bl',   colorName: 'Голубой',   hex: '#1565C0' },
    ],
    description: 'iPhone 15 в зелёном цвете — Dynamic Island и камера 48 МП.',
    specs: {
      'Экран': '6.1" Super Retina XDR',
      'Процессор': 'Apple A16 Bionic',
      'Память': '128 ГБ',
      'Камера': '48 МП + 12 МП',
      'Батарея': '3877 мАч',
      'ОС': 'iOS 17',
      'Цвет': 'Green',
    }
  },
  {
    id: 7,
    title: 'Apple iPhone 15 128Gb Yellow',
    brand: 'Apple',
    category: 'phones',
    price: 54990,
    oldPrice: null,
    rating: 4.6,
    reviews: 145,
    badge: 'new',
    inStock: true,
    images: [
      'img/yel-1.webp',
      'img/yel-2.webp',
      'img/yel-3.webp',
      'img/yel-4.webp',
      'img/yel-5.webp',
    ],
    colorVariants: [
      { id: 8, colorCode: 'grey', colorName: 'Серый',     hex: '#9E9E9E' },
      { id: 6, colorCode: 'gren', colorName: 'Зелёный',   hex: '#4CAF50' },
      { id: 3, colorCode: 'pink', colorName: 'Розовый',   hex: '#F06292' },
      { id: 7, colorCode: 'yel',  colorName: 'Жёлтый',    hex: '#FDD835' },
      { id: 2, colorCode: 'bl',   colorName: 'Голубой',   hex: '#1565C0' },
    ],
    description: 'iPhone 15 в жёлтом цвете — яркий и стильный смартфон с чипом A16 Bionic.',
    specs: {
      'Экран': '6.1" Super Retina XDR',
      'Процессор': 'Apple A16 Bionic',
      'Память': '128 ГБ',
      'Камера': '48 МП + 12 МП',
      'Батарея': '3877 мАч',
      'ОС': 'iOS 17',
      'Цвет': 'Yellow',
    }
  },
  {
    id: 8,
    title: 'Apple iPhone 15 Pro 256Gb Grey',
    brand: 'Apple',
    category: 'phones',
    price: 84990,
    oldPrice: null,
    rating: 4.7,
    reviews: 287,
    badge: null,
    inStock: false,
    images: [
      'img/grey-15-1.webp',
      'img/grey-15-2.webp',
      'img/grey-15-3.webp',
      'img/grey-15-4.webp',
      'img/grey-15-5.webp',
      'img/grey-15-6.webp',
    ],
    colorVariants: [
      { id: 8, colorCode: 'grey', colorName: 'Серый',     hex: '#9E9E9E' },
      { id: 6, colorCode: 'gren', colorName: 'Зелёный',   hex: '#4CAF50' },
      { id: 3, colorCode: 'pink', colorName: 'Розовый',   hex: '#F06292' },
      { id: 7, colorCode: 'yel',  colorName: 'Жёлтый',    hex: '#FDD835' },
      { id: 2, colorCode: 'bl',   colorName: 'Голубой',   hex: '#1565C0' },
    ],
    description: 'iPhone 15 Pro в сером цвете — премиальный смартфон с чипом A17 Pro.',
    specs: {
      'Экран': '6.1" Super Retina XDR, 120 Гц',
      'Процессор': 'Apple A17 Pro',
      'Память': '256 ГБ',
      'Камера': '48 МП + 12 МП + 12 МП',
      'Батарея': '3274 мАч',
      'ОС': 'iOS 17',
      'Цвет': 'Natural Titanium',
    }
  },

  /* ── LAPTOPS ── */
  {
    id: 9,
    title: 'Apple MacBook Air 13" M3 8GB 256GB Space Grey',
    brand: 'Apple',
    category: 'laptops',
    price: 109990,
    oldPrice: 119990,
    rating: 4.9,
    reviews: 412,
    badge: 'hit',
    inStock: true,
    images: [
      'img/mac-13-b-1.webp',
      'img/mac-13-b-2.webp',
      'img/mac-13-b-3.webp',
      'img/mac-13-b-4.webp',
      'img/mac-13-b-5.webp',
      'img/mac-13-b-6.webp',
    ],
    colorVariants: [
      { id: 9,  colorCode: 'b',  colorName: 'Чёрный',  hex: '#2b2b2b' },
      { id: 10, colorCode: 'bl', colorName: 'Голубой', hex: '#1c3555' },
    ],
    description: 'MacBook Air 13" с чипом M3 — тончайший и мощнейший ноутбук Apple для повседневных задач.',
    specs: {
      'Дисплей': '13.6" Liquid Retina',
      'Процессор': 'Apple M3 (8 ядер)',
      'ОЗУ': '8 ГБ',
      'Накопитель': '256 ГБ SSD',
      'Видео': 'GPU 10 ядер',
      'Батарея': 'до 18 часов',
      'ОС': 'macOS Sequoia',
      'Цвет': 'Space Grey',
    }
  },
  {
    id: 10,
    title: 'Apple MacBook Air 13" M3 8GB 256GB Midnight',
    brand: 'Apple',
    category: 'laptops',
    price: 109990,
    oldPrice: null,
    rating: 4.9,
    reviews: 380,
    badge: null,
    inStock: true,
    images: [
      'img/mac-13-bl-1.webp',
      'img/mac-13-bl-2.webp',
      'img/mac-13-bl-3.webp',
      'img/mac-13-bl-4.webp',
      'img/mac-13-bl-5.webp',
      'img/mac-13-bl-6.webp',
    ],
    colorVariants: [
      { id: 9,  colorCode: 'b',  colorName: 'Чёрный',  hex: '#2b2b2b' },
      { id: 10, colorCode: 'bl', colorName: 'Голубой', hex: '#1c3555' },
    ],
    description: 'MacBook Air 13" с чипом M3 в цвете Midnight — элегантный ноутбук с высокой автономностью.',
    specs: {
      'Дисплей': '13.6" Liquid Retina',
      'Процессор': 'Apple M3 (8 ядер)',
      'ОЗУ': '8 ГБ',
      'Накопитель': '256 ГБ SSD',
      'Видео': 'GPU 10 ядер',
      'Батарея': 'до 18 часов',
      'ОС': 'macOS Sequoia',
      'Цвет': 'Midnight',
    }
  },
  {
    id: 11,
    title: 'Apple MacBook Pro 15" M4 16GB 512GB Space Black',
    brand: 'Apple',
    category: 'laptops',
    price: 189990,
    oldPrice: null,
    rating: 5.0,
    reviews: 156,
    badge: 'new',
    inStock: true,
    images: [
      'img/mac-15-b-1.webp',
      'img/mac-15-b-2.webp',
      'img/mac-15-b-3.webp',
      'img/mac-15-b-4.webp',
      'img/mac-15-b-5.webp',
      'img/mac-15-b-6.webp',
    ],
    colorVariants: [
      { id: 11, colorCode: 'b',  colorName: 'Чёрный',  hex: '#2b2b2b' },
      { id: 12, colorCode: 'bl', colorName: 'Голубой', hex: '#1c3555' },
    ],
    description: 'MacBook Pro 15" с M4 — профессиональная мощь в элегантном корпусе Space Black.',
    specs: {
      'Дисплей': '15.3" Liquid Retina XDR, 120 Гц',
      'Процессор': 'Apple M4 (10 ядер)',
      'ОЗУ': '16 ГБ',
      'Накопитель': '512 ГБ SSD',
      'Видео': 'GPU 10 ядер',
      'Батарея': 'до 22 часов',
      'ОС': 'macOS Sequoia',
      'Цвет': 'Space Black',
    }
  },
  {
    id: 12,
    title: 'Apple MacBook Pro 15" M4 16GB 512GB Midnight',
    brand: 'Apple',
    category: 'laptops',
    price: 189990,
    oldPrice: 209990,
    rating: 4.9,
    reviews: 98,
    badge: 'sale',
    inStock: true,
    images: [
      'img/mac-15-bl-1.webp',
      'img/mac-15-bl-2.webp',
      'img/mac-15-bl-3.webp',
      'img/mac-15-bl-4.webp',
      'img/mac-15-bl-5.webp',
      'img/mac-15-bl-6.webp',
    ],
    colorVariants: [
      { id: 11, colorCode: 'b',  colorName: 'Чёрный',  hex: '#2b2b2b' },
      { id: 12, colorCode: 'bl', colorName: 'Голубой', hex: '#1c3555' },
    ],
    description: 'MacBook Pro 15" с M4 в цвете Midnight — мощь и стиль для профессионалов.',
    specs: {
      'Дисплей': '15.3" Liquid Retina XDR, 120 Гц',
      'Процессор': 'Apple M4 (10 ядер)',
      'ОЗУ': '16 ГБ',
      'Накопитель': '512 ГБ SSD',
      'Видео': 'GPU 10 ядер',
      'Батарея': 'до 22 часов',
      'ОС': 'macOS Sequoia',
      'Цвет': 'Midnight',
    }
  },

  /* ── HEADPHONES ── */
  {
    id: 13,
    title: 'Apple AirPods Max Vanilla',
    brand: 'Apple',
    category: 'headphones',
    price: 50990,
    oldPrice: 59990,
    rating: 4.9,
    reviews: 287,
    badge: 'hit',
    inStock: true,
    images: [
      'img/airpods-max-v-1.webp',
      'img/airpods-max-v-2.webp',
      'img/airpods-max-v-3.webp',
    ],
    description: 'AirPods Max — накладные наушники Apple с активным шумоподавлением и пространственным звуком.',
    specs: {
      'Тип': 'Накладные, беспроводные',
      'ANC': 'Активное шумоподавление',
      'Пространственный звук': 'Да',
      'Батарея': 'до 20 часов',
      'Чип': 'Apple H1 (x2)',
      'Цвет': 'Vanilla',
    }
  },
  {
    id: 14,
    title: 'Apple AirPods Max Black',
    brand: 'Apple',
    category: 'headphones',
    price: 50990,
    oldPrice: null,
    rating: 4.9,
    reviews: 320,
    badge: null,
    inStock: true,
    images: [
      'img/airpods-max-b-1.webp',
      'img/airpods-max-b-2.webp',
      'img/airpods-max-b-3.webp',
      'img/airpods-max-b-4.webp',
      'img/airpods-max-b-5.webp',
      'img/airpods-max-b-6.webp',
      'img/airpods-max-b-7.webp',
      'img/airpods-max-b-8.webp',
    ],
    description: 'AirPods Max в чёрном — премиальные наушники с непревзойдённым качеством звука.',
    specs: {
      'Тип': 'Накладные, беспроводные',
      'ANC': 'Активное шумоподавление',
      'Пространственный звук': 'Да',
      'Батарея': 'до 20 часов',
      'Чип': 'Apple H1 (x2)',
      'Цвет': 'Black',
    }
  },
  {
    id: 15,
    title: 'Apple AirPods 4',
    brand: 'Apple',
    category: 'headphones',
    price: 14990,
    oldPrice: 17990,
    rating: 4.7,
    reviews: 445,
    badge: 'sale',
    inStock: true,
    images: [
      'img/airpods-4-w-1.webp',
      'img/airpods-4-w-2.webp',
      'img/airpods-4-w-3.webp',
      'img/airpods-4-w-4.webp',
      'img/airpods-4-w-5.webp',
    ],
    description: 'AirPods 4 — новое поколение вкладышей Apple с улучшенным звуком и посадкой.',
    specs: {
      'Тип': 'Вкладыши, беспроводные',
      'ANC': 'Нет',
      'Чип': 'Apple H2',
      'Батарея': 'до 5 часов + кейс',
      'Цвет': 'White',
    }
  },
  {
    id: 16,
    title: 'Apple AirPods 3',
    brand: 'Apple',
    category: 'headphones',
    price: 11990,
    oldPrice: null,
    rating: 4.6,
    reviews: 612,
    badge: null,
    inStock: true,
    images: [
      'img/airpods-3-w-1.webp',
      'img/airpods-3-w-2.webp',
      'img/airpods-3-w-3.webp',
      'img/airpods-3-w-4.webp',
      'img/airpods-3-w-5.webp',
      'img/airpods-3-w-6.webp',
      'img/airpods-3-w-7.webp',
      'img/airpods-3-w-8.webp',
    ],
    description: 'AirPods 3 — вкладыши Apple с пространственным звуком и влагозащитой IPX4.',
    specs: {
      'Тип': 'Вкладыши, беспроводные',
      'Пространственный звук': 'Да',
      'Чип': 'Apple H1',
      'Батарея': 'до 6 часов + кейс',
      'Влагозащита': 'IPX4',
      'Цвет': 'White',
    }
  },

  /* ── WATCHES ── */
  {
    id: 17,
    title: 'Apple Watch Series 11 45mm Gold Aluminium',
    brand: 'Apple',
    category: 'watch',
    price: 44990,
    oldPrice: null,
    rating: 4.9,
    reviews: 198,
    badge: 'new',
    inStock: true,
    images: [
      'img/watch-11-g-1.webp',
      'img/watch-11-g-2.webp',
      'img/watch-11-g-3.webp',
      'img/watch-11-g-4.webp',
      'img/watch-11-g-5.webp',
      'img/watch-11-g-6.webp',
      'img/watch-11-g-7.webp',
      'img/watch-11-g-8.webp',
      'img/watch-11-g-9.webp',
    ],
    description: 'Apple Watch Series 11 в золотом корпусе — новейшие умные часы с расширенными функциями здоровья.',
    specs: {
      'Корпус': '45 мм, алюминий Gold',
      'Дисплей': 'LTPO OLED',
      'Мониторинг': 'ЧСС, SpO2, ЭКГ, сон',
      'Водозащита': '50 м',
      'ОС': 'watchOS 11',
    }
  },
  {
    id: 18,
    title: 'Apple Watch Series 11 45mm White Aluminium',
    brand: 'Apple',
    category: 'watch',
    price: 44990,
    oldPrice: 49990,
    rating: 4.8,
    reviews: 234,
    badge: 'sale',
    inStock: true,
    images: [
      'img/watch-11-w-1.webp',
      'img/watch-11-w-2.webp',
      'img/watch-11-w-3.webp',
      'img/watch-11-w-4.webp',
      'img/watch-11-w-5.webp',
      'img/watch-11-w-6.webp',
      'img/watch-11-w-7.webp',
      'img/watch-11-w-8.webp',
      'img/watch-11-w-9.webp',
    ],
    description: 'Apple Watch Series 11 в белом — стильные умные часы с мощным здоровье-мониторингом.',
    specs: {
      'Корпус': '45 мм, алюминий White',
      'Дисплей': 'LTPO OLED',
      'Мониторинг': 'ЧСС, SpO2, ЭКГ, сон',
      'Водозащита': '50 м',
      'ОС': 'watchOS 11',
    }
  },
  {
    id: 19,
    title: 'Apple Watch SE 44mm Black Aluminium',
    brand: 'Apple',
    category: 'watch',
    price: 24990,
    oldPrice: null,
    rating: 4.6,
    reviews: 445,
    badge: null,
    inStock: true,
    images: [
      'img/watch-b-1.webp',
      'img/watch-b-2.webp',
      'img/watch-b-3.webp',
      'img/watch-b-4.webp',
      'img/watch-b-5.webp',
      'img/watch-b-6.webp',
      'img/watch-b-7.webp',
      'img/watch-b-8.webp',
    ],
    description: 'Apple Watch SE — доступные умные часы с основными функциями здоровья и фитнеса.',
    specs: {
      'Корпус': '44 мм, алюминий Midnight',
      'Дисплей': 'LTPO OLED',
      'Мониторинг': 'ЧСС, SpO2, сон',
      'Водозащита': '50 м',
      'ОС': 'watchOS 11',
    }
  },
  {
    id: 20,
    title: 'Apple Watch SE 44mm White Aluminium',
    brand: 'Apple',
    category: 'watch',
    price: 24990,
    oldPrice: 28990,
    rating: 4.6,
    reviews: 378,
    badge: 'sale',
    inStock: true,
    images: [
      'img/watch-w-1.webp',
      'img/watch-w-2.webp',
      'img/watch-w-3.webp',
      'img/watch-w-4.webp',
      'img/watch-w-5.webp',
      'img/watch-w-6.webp',
      'img/watch-w-7.webp',
      'img/watch-w-8.webp',
    ],
    description: 'Apple Watch SE в белом — доступный и функциональный выбор.',
    specs: {
      'Корпус': '44 мм, алюминий Starlight',
      'Дисплей': 'LTPO OLED',
      'Мониторинг': 'ЧСС, SpO2, сон',
      'Водозащита': '50 м',
      'ОС': 'watchOS 11',
    }
  },

  /* ── VACUUM ── */
  {
    id: 21,
    title: 'Пылесос Dreame H12 Pro Беспроводной',
    brand: 'Dreame',
    category: 'vacuum',
    price: 34990,
    oldPrice: 39990,
    rating: 4.8,
    reviews: 213,
    badge: 'sale',
    inStock: true,
    images: [
      'img/vacuum-dreame-b-1.webp',
      'img/vacuum-dreame-b-2.webp',
      'img/vacuum-dreame-b-3.webp',
      'img/vacuum-dreame-b-4.webp',
      'img/vacuum-dreame-b-5.webp',
      'img/vacuum-dreame-b-6.webp',
      'img/vacuum-dreame-b-7.webp',
      'img/vacuum-dreame-b-8.webp',
      'img/vacuum-dreame-b-9.webp',
      'img/vacuum-dreame-b-10.webp',
    ],
    description: 'Dreame H12 Pro — мощный беспроводной пылесос-швабра для сухой и влажной уборки.',
    specs: {
      'Тип': 'Беспроводной, вертикальный',
      'Мощность всасывания': '17 000 Па',
      'Ёмкость бака': '0.9 л',
      'Батарея': 'до 35 мин',
      'Уборка': 'Сухая и влажная',
    }
  },
  {
    id: 22,
    title: 'Пылесос DEXP VS-100B Вертикальный',
    brand: 'DEXP',
    category: 'vacuum',
    price: 8990,
    oldPrice: null,
    rating: 4.2,
    reviews: 87,
    badge: null,
    inStock: true,
    images: [
      'img/vacuum-dexp-b-1.webp',
      'img/vacuum-dexp-b-2.webp',
      'img/vacuum-dexp-b-3.webp',
      'img/vacuum-dexp-b-4.webp',
      'img/vacuum-dexp-b-5.webp',
      'img/vacuum-dexp-b-6.webp',
      'img/vacuum-dexp-b-7.webp',
    ],
    description: 'DEXP VS-100B — компактный вертикальный пылесос для ежедневной уборки.',
    specs: {
      'Тип': 'Проводной, вертикальный',
      'Мощность': '1800 Вт',
      'Тип пыленакопителя': 'Циклонный',
      'Вес': '2.1 кг',
    }
  },
  {
    id: 23,
    title: 'Пылесос DEXP VS-200W Вертикальный',
    brand: 'DEXP',
    category: 'vacuum',
    price: 9490,
    oldPrice: 11990,
    rating: 4.3,
    reviews: 64,
    badge: 'sale',
    inStock: true,
    images: [
      'img/vacuum-dexp-w-1.webp',
      'img/vacuum-dexp-w-2.webp',
      'img/vacuum-dexp-w-3.webp',
      'img/vacuum-dexp-w-4.webp',
      'img/vacuum-dexp-w-5.webp',
      'img/vacuum-dexp-w-6.webp',
      'img/vacuum-dexp-w-7.webp',
      'img/vacuum-dexp-w-8.webp',
    ],
    description: 'DEXP VS-200W — вертикальный пылесос в белом цвете с хорошей всасывающей мощностью.',
    specs: {
      'Тип': 'Проводной, вертикальный',
      'Мощность': '2000 Вт',
      'Тип пыленакопителя': 'Мешок',
      'Вес': '2.4 кг',
    }
  },
  {
    id: 24,
    title: 'Пылесос Kitfort KT-590 Робот',
    brand: 'Kitfort',
    category: 'vacuum',
    price: 19990,
    oldPrice: null,
    rating: 4.5,
    reviews: 134,
    badge: null,
    inStock: true,
    images: [
      'img/vacuum-kitfort-w-1.webp',
      'img/vacuum-kitfort-w-2.webp',
      'img/vacuum-kitfort-w-3.webp',
      'img/vacuum-kitfort-w-4.webp',
      'img/vacuum-kitfort-w-5.webp',
      'img/vacuum-kitfort-w-6.webp',
    ],
    description: 'Kitfort KT-590 — умный робот-пылесос с навигацией и управлением со смартфона.',
    specs: {
      'Тип': 'Робот-пылесос',
      'Мощность всасывания': '2500 Па',
      'Ёмкость контейнера': '0.6 л',
      'Батарея': 'до 120 мин',
      'Управление': 'Приложение',
    }
  },
  {
    id: 25,
    title: 'Пылесос Kitfort KT-551 Вертикальный Красный',
    brand: 'Kitfort',
    category: 'vacuum',
    price: 12990,
    oldPrice: 14990,
    rating: 4.4,
    reviews: 98,
    badge: 'sale',
    inStock: true,
    images: [
      'img/vacuum-kitfortKT-r-1.webp',
      'img/vacuum-kitfortKT-r-2.webp',
      'img/vacuum-kitfortKT-r-3.webp',
      'img/vacuum-kitfortKT-r-4.webp',
      'img/vacuum-kitfortKT-r-5.webp',
    ],
    description: 'Kitfort KT-551 — яркий вертикальный беспроводной пылесос для удобной уборки.',
    specs: {
      'Тип': 'Беспроводной, вертикальный',
      'Мощность': '120 Вт',
      'Батарея': 'до 40 мин',
      'Вес': '1.5 кг',
      'Цвет': 'Красный',
    }
  },
  {
    id: 26,
    title: 'Пылесос Kitfort KT-551 Вертикальный Белый',
    brand: 'Kitfort',
    category: 'vacuum',
    price: 12990,
    oldPrice: null,
    rating: 4.4,
    reviews: 76,
    badge: null,
    inStock: true,
    images: [
      'img/vacuum-kitfortKT-w-1.webp',
      'img/vacuum-kitfortKT-w-2.webp',
      'img/vacuum-kitfortKT-w-3.webp',
      'img/vacuum-kitfortKT-w-4.webp',
      'img/vacuum-kitfortKT-w-5.webp',
    ],
    description: 'Kitfort KT-551 в белом — удобный беспроводной пылесос для дома.',
    specs: {
      'Тип': 'Беспроводной, вертикальный',
      'Мощность': '120 Вт',
      'Батарея': 'до 40 мин',
      'Вес': '1.5 кг',
      'Цвет': 'Белый',
    }
  },
  {
    id: 27,
    title: 'Пылесос Kitfort KT-99 Вертикальный Белый',
    brand: 'Kitfort',
    category: 'vacuum',
    price: 15990,
    oldPrice: null,
    rating: 4.6,
    reviews: 112,
    badge: 'new',
    inStock: true,
    images: [
      'img/vacuum-kitfortKT99-w-1.webp',
      'img/vacuum-kitfortKT99-w-2.webp',
      'img/vacuum-kitfortKT99-w-3.webp',
      'img/vacuum-kitfortKT99-w-4.webp',
      'img/vacuum-kitfortKT99-w-5.webp',
      'img/vacuum-kitfortKT99-w-6.webp',
      'img/vacuum-kitfortKT99-w-7.webp',
      'img/vacuum-kitfortKT99-w-8.webp',
      'img/vacuum-kitfortKT99-w-9.webp',
    ],
    description: 'Kitfort KT-99 — мощный вертикальный беспроводной пылесос нового поколения.',
    specs: {
      'Тип': 'Беспроводной, вертикальный',
      'Мощность': '160 Вт',
      'Батарея': 'до 50 мин',
      'Вес': '1.8 кг',
    }
  },
  {
    id: 28,
    title: 'Пылесос DEXP Робот G20',
    brand: 'DEXP',
    category: 'vacuum',
    price: 22990,
    oldPrice: 26990,
    rating: 4.5,
    reviews: 89,
    badge: 'sale',
    inStock: true,
    images: [
      'img/vacuum-g20-w-1.webp',
      'img/vacuum-g20-w-2.webp',
      'img/vacuum-g20-w-3.webp',
      'img/vacuum-g20-w-4.webp',
      'img/vacuum-g20-w-5.webp',
      'img/vacuum-g20-w-6.webp',
      'img/vacuum-g20-w-7.webp',
      'img/vacuum-g20-w-8.webp',
      'img/vacuum-g20-w-9.webp',
    ],
    description: 'DEXP G20 — робот-пылесос с картографированием помещения и влажной уборкой.',
    specs: {
      'Тип': 'Робот-пылесос',
      'Мощность всасывания': '3000 Па',
      'Ёмкость контейнера': '0.4 л',
      'Батарея': 'до 150 мин',
      'Уборка': 'Сухая и влажная',
    }
  },

  /* ── DRYER ── */
  {
    id: 29,
    title: 'Dyson Supersonic HD15 Чёрный',
    brand: 'Dyson',
    category: 'dryer',
    price: 39990,
    oldPrice: 44990,
    rating: 4.9,
    reviews: 312,
    badge: 'hit',
    inStock: true,
    images: [
      'img/dryer-dyson-b-1.webp',
      'img/dryer-dyson-b-2.webp',
      'img/dryer-dyson-b-3.webp',
      'img/dryer-dyson-b-4.webp',
      'img/dryer-dyson-b-5.webp',
      'img/dryer-dyson-b-6.webp',
      'img/dryer-dyson-b-7.webp',
      'img/dryer-dyson-b-8.webp',
      'img/dryer-dyson-b-9.webp',
    ],
    description: 'Dyson Supersonic HD15 — профессиональный фен с интеллектуальным контролем температуры.',
    specs: {
      'Мощность': '1600 Вт',
      'Скорости': '3 скорости',
      'Температура': '4 режима',
      'Технология': 'Цифровой мотор V9',
      'Цвет': 'Чёрный/Медь',
    }
  },
  {
    id: 30,
    title: 'Dyson Airwrap Фиолетовый',
    brand: 'Dyson',
    category: 'dryer',
    price: 54990,
    oldPrice: null,
    rating: 4.8,
    reviews: 187,
    badge: null,
    inStock: true,
    images: [
      'img/dryer-dyson-p-1.webp',
      'img/dryer-dyson-p-2.webp',
      'img/dryer-dyson-p-3.webp',
      'img/dryer-dyson-p-4.webp',
      'img/dryer-dyson-p-5.webp',
      'img/dryer-dyson-p-6.webp',
      'img/dryer-dyson-p-7.webp',
      'img/dryer-dyson-p-8.webp',
    ],
    description: 'Dyson Airwrap — многофункциональный стайлер для завивки, выпрямления и сушки волос.',
    specs: {
      'Мощность': '1300 Вт',
      'Насадки': '6 насадок в комплекте',
      'Технология': 'Эффект Коанда',
      'Температура': 'Интеллектуальный контроль',
      'Цвет': 'Purple',
    }
  },
  {
    id: 31,
    title: 'Фен Aceline AF-200 Белый',
    brand: 'Aceline',
    category: 'dryer',
    price: 3990,
    oldPrice: 4990,
    rating: 4.2,
    reviews: 234,
    badge: 'sale',
    inStock: true,
    images: [
      'img/dryer-aceline-w-1.webp',
      'img/dryer-aceline-w-2.webp',
      'img/dryer-aceline-w-3.webp',
      'img/dryer-aceline-w-4.webp',
      'img/dryer-aceline-w-5.webp',
      'img/dryer-aceline-w-6.webp',
      'img/dryer-aceline-w-7.webp',
      'img/dryer-aceline-w-8.webp',
      'img/dryer-aceline-w-9.webp',
    ],
    description: 'Aceline AF-200 — мощный бытовой фен с ионизацией для ухода за волосами.',
    specs: {
      'Мощность': '2200 Вт',
      'Скорости': '2 скорости',
      'Температура': '3 режима',
      'Ионизация': 'Да',
      'Цвет': 'Белый',
    }
  },
  {
    id: 32,
    title: 'Фен Aceline AF-300 Серый',
    brand: 'Aceline',
    category: 'dryer',
    price: 4990,
    oldPrice: null,
    rating: 4.3,
    reviews: 156,
    badge: null,
    inStock: true,
    images: [
      'img/dryer-aceline-g-1.webp',
      'img/dryer-aceline-g-2.webp',
      'img/dryer-aceline-g-3.webp',
      'img/dryer-aceline-g-4.webp',
      'img/dryer-aceline-g-5.webp',
      'img/dryer-aceline-g-6.webp',
      'img/dryer-aceline-g-7.webp',
      'img/dryer-aceline-g-8.webp',
    ],
    description: 'Aceline AF-300 — профессиональный фен с серым дизайном и мощностью 2400 Вт.',
    specs: {
      'Мощность': '2400 Вт',
      'Скорости': '2 скорости',
      'Температура': '3 режима',
      'Ионизация': 'Да',
      'Цвет': 'Серый',
    }
  },

];

/* ── HELPERS ── */

function getProductById(id) {
  return PRODUCTS.find(p => p.id === Number(id)) || null;
}

function getProductsByCategory(category) {
  if (!category || category === 'all') return PRODUCTS;
  return PRODUCTS.filter(p => p.category === category);
}

const CATEGORY_LABELS = {
  phones:     'Смартфоны',
  laptops:    'Ноутбуки',
  headphones: 'Наушники',
  watch:      'Умные часы',
  vacuum:     'Пылесосы',
  dryer:      'Фены',
  all:        'Все товары',
};